### ISSUE TITLE
All machines in DB are visible as machines of Factory

### ISSUE THREAD

**Issue by aaumkar** [ameysatwe/Factory-Frontend#1]
# Not only the connected machines are visible

## Please refer to the screenshots

![image](https://user-images.githubusercontent.com/43928050/95344721-91151180-08d7-11eb-8918-fd161f4996a9.png)
Above is the `Factory` Table, as you can see only 2 machines are allocated

---
![image](https://user-images.githubusercontent.com/43928050/95345055-f9fc8980-08d7-11eb-8f27-661069334488.png)
Above is the `Machines` Table, the Machine `M3x12` is not allotted to factory, but just exists in table.

---
![image](https://user-images.githubusercontent.com/43928050/95345422-5364b880-08d8-11eb-8025-369685af2b89.png)
The dashboard shows the machines not installed too.

The Dashboard shows the `machine`s which are not installed on the `factory`

**Comment by ameysatwe** [comment]
This is good to close right?

**Comment by aaumkar** [comment]
Yes ofcourse
